name: isofit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.9=hd590300_0
  - aom=3.5.0=h27087fc_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.7.0=hf8751d9_2
  - aws-c-cal=0.6.0=h93469e0_0
  - aws-c-common=0.8.23=hd590300_0
  - aws-c-compression=0.2.17=h862ab75_1
  - aws-c-event-stream=0.3.1=h9599702_1
  - aws-c-http=0.7.11=hbe98c3e_0
  - aws-c-io=0.13.28=h3870b5a_0
  - aws-c-mqtt=0.8.14=h2e270ba_2
  - aws-c-s3=0.3.13=heb0bb06_2
  - aws-c-sdkutils=0.1.11=h862ab75_1
  - aws-checksums=0.1.16=h862ab75_1
  - awscli
  - aws-crt-cpp=0.20.3=he9c0e7f_4
  - aws-sdk-cpp=1.10.57=hbc2ea52_17
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.4=h0f2a231_0
  - boost-cpp=1.78.0=h6582d0a_3
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py310hd8f1fbe_9
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - c-blosc2=2.10.0=hb4ffafa_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=hbbf8b49_1016
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.3.0=hbdc6101_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.6=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - curl=8.2.1=hca28451_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - eccodes=2.31.0=h73bf81c_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filelock=3.12.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.12.1=hca18f0e_1
  - freexl=1.0.6=h166bdaf_1
  - gdal=3.7.1
  - geos=3.12.0=h59595ed_0
  - geotiff=1.7.1=h22adcc9_11
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.76.4=hfc55251_0
  - glib-tools=2.76.4=hfc55251_0
  - gmp=6.2.1=h295c915_3
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.5=hf7dbed1_0
  - gstreamer=1.22.5=h98fc4e7_0
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.1=nompi_h4f84152_100
  - icu=72.1=hcb278e6_0
  - identify=2.5.26=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - imageio=2.31.1=pyh24c5eb1_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jasper=4.0.0=h32699f2_1
  - joblib=1.3.0=pyhd8ed1ab_1
  - json-c=0.16=hc379101_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter_client=7.4.9=py310h06a4308_0
  - jupyter_core=5.3.0=py310h06a4308_0
  - jupyter_events=0.6.3=py310h06a4308_0
  - jupyter_server=1.23.4=py310h06a4308_0
  - jupyter_server_fileid=0.9.0=py310h06a4308_0
  - jupyter_server_ydoc=0.8.0=py310h06a4308_1
  - jupyter_ydoc=0.2.4=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py310h06a4308_0
  - jxrlib=1.1=h7f98852_2
  - kealib=1.5.1=h3e6883b_4
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.1=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.2=pyhd8ed1ab_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libarchive=3.6.2=h039dbb9_1
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=17_linux64_openblas
  - libclang13=15.0.7=default_h9986a30_3
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.2.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libglu=9.0.0=hac7e632_1002
  - libgomp=13.1.0=he5830b7_0
  - libgpg-error=1.47=h71f35ed_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - libkml=1.3.0=h37653c0_1015
  - liblapack=3.9.0=17_linux64_openblas
  - libllvm15=15.0.7=h5cf9203_3
  - libnetcdf=4.9.2=nompi_h7e745eb_109
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hfc447b1_2
  - librttopo=1.1.0=hb58d41b_14
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialite=5.0.1=h15f6e67_28
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libsystemd0=254=h3516f8a_0
  - libtiff=4.5.1=h8b53f26_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.4=h0d562d8_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=hd590300_5
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - matplotlib-base=3.7.2=py310hf38f957_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.31.3=hcb278e6_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_2
  - mysql-libs=8.0.33=hca2cd23_2
  - ncurses=6.4=hcb278e6_0
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.2=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pep8=1.7.1=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.07.0=hd18248d_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=h8972f4a_2
  - pre-commit=3.3.3=pyha770c72_0
  - proj=9.2.1=ha643af7_0
  - prometheus_client=0.14.1=py310h06a4308_0
  - protobuf
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=16.1=hb77b528_4
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_4
  - pytest=7.4.0=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytorch=2.0.1=cpu_py310hab5cca8_0
  - pytz=2023.3=pyhd8ed1ab_0
  - qt-main=5.15.8=h7fe3ca9_15
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - s2n=1.3.46=h06160fa_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - spectral=0.23.1=pyh1a96a4e_0
  - sqlite=3.42.0=h2c6b66d_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2023.7.18=pyhd8ed1ab_0
  - tiledb=2.16.1=hf0b6e87_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tzcode=2023c=h0b41bf4_0
  - tzdata=2023c=h71feb2d_0
  - utm=0.7.0=pyhd8ed1ab_0
  - virtualenv=20.24.2=pyhd8ed1ab_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xerces-c=3.2.4=h8d71039_2
  - xkeyboard-config=2.39=hd590300_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zfp=1.0.0=h27087fc_3
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.2=hfc55251_7
  - pip:
    - absl-py==1.4.0
    - affine==2.4.0
    - aiofiles==22.1.0
    - aiosignal==1.3.1
    - aiosqlite==0.18.0
    - alabaster==0.7.13
    - anyio==3.5.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - asttokens==2.2.1
    - astunparse==1.6.3
    - attrs==23.1.0
    - babel==2.11.0
    - beautifulsoup4==4.12.2
    - brotli==1.0.9
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - cftime==1.6.2
    - click-plugins==1.1.1
    - cligj==0.7.2
    - comm==0.1.2
    - contourpy==1.1.0
    - cryptography==41.0.3
    - debugpy==1.6.7
    - dnspython==2.4.2
    - docutils==0.20.1
    - earthengine-api==0.1.369
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fiona==1.9.4.post1
    - flatbuffers==23.5.26
    - fonttools==4.42.0
    - frozenlist==1.4.0
    - gast==0.4.0
    - geopandas==0.14.0
    - gmpy2==2.1.2
    - google-api-core==2.11.1
    - google-api-python-client==2.99.0
    - google-auth==2.22.0
    - google-auth-httplib2==0.1.1
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.3
    - google-cloud-storage==2.10.0
    - google-crc32c==1.5.0
    - google-pasta==0.2.0
    - google-resumable-media==2.6.0
    - googleapis-common-protos==1.60.0
    - grpcio==1.56.2
    - h5py==3.9.0
    - httplib2==0.22.0
    - imagecodecs==2023.7.10
    - imagesize==1.4.1
    - ipdb==0.13.13
    - ipykernel==6.25.0
    - ipython==8.14.0
    - isofit==2.10.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - jsonschema-specifications==2023.7.1
    - jupyter-client==7.4.9
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==1.23.4
    - jupyter-server-fileid==0.9.0
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.4
    - jupyterlab==3.6.3
    - jupyterlab-server==2.22.0
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==16.0.6
    - markdown==3.4.4
    - markupsafe==2.1.1
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mistune==0.8.4
    - mpmath==1.3.0
    - msgpack==1.0.5
    - nbclassic==0.5.5
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.7.0
    - ndsplines==0.1.4
    - nest-asyncio==1.5.6
    - netcdf4==1.6.4
    - notebook==6.5.4
    - notebook-shim==0.2.2
    - numpy==1.24.3
    - oauthlib==3.2.2
    - opencv-python==4.8.0.74
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - pandas==2.0.3
    - papermill
    - parse==1.19.1
    - pillow==10.0.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.36
    - psutil==5.9.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycurl==7.45.2
    - pygments==2.15.1
    - pygrib==2.1.4
    - pymongo==4.5.0
    - pyproj==3.6.0
    - pyqt5==5.15.9
    - pyqt5-sip==12.12.2
    - pyrsistent==0.18.0
    - pysocks==1.7.1
    - python-json-logger==2.0.7
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==23.2.0
    - rasterio==1.3.8
    - ray==2.6.1
    - referencing==0.30.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.9.2
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.3.0
    - scipy==1.11.1
    - segment-anything==1.0
    - shapely==2.0.1
    - sip==6.7.11
    - sniffio==1.2.0
    - snowballstemmer==2.2.0
    - snuggs==1.4.7
    - soupsieve==2.4
    - sphinx==7.1.2
    - sphinx-autodoc-typehints==1.24.0
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.6.2
    - sympy==1.11.1
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.1
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.33.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - testpath==0.6.0
    - torch==2.0.1
    - torchvision==0.15.2
    - tornado==6.3.2
    - traitlets==5.7.1
    - typing-extensions==4.5.0
    - unity-sds-client==0.3.0
    - ukkonen==1.0.1
    - unicodedata2==15.0.0
    - uritemplate==4.1.1
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - websocket-client==0.58.0
    - werkzeug==2.3.6
    - wrapt==1.15.0
    - xarray==2024.6.0
    - xxhash==3.3.0
    - y-py==0.5.9
    - ypy-websocket==0.8.2
prefix: /tmp/miniconda/envs/isofit_env